# ~/.config/hypr/hyprlock.conf

general {
    grace = 30
    hide_cursor = true
    no_fade_in = false
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    contrast = 0.9
    brightness = 0.45
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    fade_on_empty = true
    rounding = -1
    outer_color = rgb(fc3744)
    inner_color = rgb(313244)
    font_color = rgb(efede3)
    check_color = rgb(a6e3a1)
    fail_color = rgb(fc3744)
    placeholder_text = <i>put yo password unc...</i>
    hide_input = false
    position = 0, 40
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(f90223)
    font_size = 256
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -260
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:5000] bat=$(cat /sys/class/power_supply/BAT*/capacity 2>/dev/null | head -1); ram=$(free | awk '/^Mem:/{printf "%.0f", $3/$2*100}'); echo "  ${ram}%    ${bat:-N/A}%"
    color = rgb(6c7086)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -420
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgb(a6adc5)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, -100
    halign = center
    valign = center
}
