# Volkanos btop configuration
color_theme = "mono-red"
theme_background = True
truecolor = True
force_tty = False
rounded_corners = False
graph_symbol = "block"
graph_symbol_cpu = "block"
graph_symbol_mem = "block"
graph_symbol_net = "block"
graph_symbol_proc = "block"
show_cpu_freq = True
show_gpu_info = "Auto"
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
tree_depth = 3
vim_keys = False
