# Volkanos — btop theme
# Red / dark minimal palette

theme[main_bg]="#1f222d"
theme[main_fg]="#f9f9f9"
theme[title]="#f9f9f9"
theme[hi_fg]="#fc161a"
theme[selected_bg]="#1f222d"
theme[selected_fg]="#fc161a"
theme[inactive_fg]="#8384a0"
theme[graph_text]="#f9f9f9"
theme[meter_bg]="#383131"
theme[proc_misc]="#d84e50"

theme[cpu_box]="#fc161a"
theme[mem_box]="#fc161a"
theme[net_box]="#fc161a"
theme[proc_box]="#fc161a"
theme[div_line]="#383131"

theme[temp_start]="#d84e50"
theme[temp_mid]="#fc161a"
theme[temp_end]="#e0283b"

theme[cpu_start]="#d84e50"
theme[cpu_mid]="#fc161a"
theme[cpu_end]="#e0283b"

theme[free_start]="#8384a0"
theme[free_mid]="#d84e50"
theme[free_end]="#fc161a"

theme[cached_start]="#383131"
theme[cached_mid]="#843335"
theme[cached_end]="#d84e50"

theme[available_start]="#8384a0"
theme[available_mid]="#d84e50"
theme[available_end]="#fc161a"

theme[used_start]="#d84e50"
theme[used_mid]="#fc161a"
theme[used_end]="#e0283b"

theme[download_start]="#8384a0"
theme[download_mid]="#d84e50"
theme[download_end]="#fc161a"

theme[upload_start]="#d84e50"
theme[upload_mid]="#fc161a"
theme[upload_end]="#e0283b"

theme[process_start]="#8384a0"
theme[process_mid]="#d84e50"
theme[process_end]="#fc161a"
